### PR TITLE
Add ability to insert update delete records and upgrade to ext-mongodb

### PR DESCRIPTION
**Pull request by Qwedir**
- add ability to insert update delete records 
- upgrade to ext-mongodb

### CODE REVIEW

**Comment by jesobreira** [comment]
Will this ever be merged? OP has even deleted the repo...

**Comment by Qwedir** [comment]
I think no because OP said 

"This project is highly experimental. Please do not bother to open issues for missing functionality."

When i did this pull request I haven't seen it.

**Comment by jesobreira** [comment]
I believe you did a great progress and sadly this repo seems to be abandoned (last commit 6 years ago). Would you be willing to upload your version somewhere so we could take it forward? I can contribute as well.

**Comment by Qwedir** [comment]
This pull request all what I did. Unfortunately repository was deleted. But it's not problem you can restore this code from PR if you need.

**Pull request closed without merging**
